* Glitches & Fixes
** Anki
*** To avoid starting with the UI tearing up 
    ANKI_NOHIGHDPI=1 anki
** mbsync
*** Yahoo required creating a separate 'app password' to be used for the client.
** Firefox
*** browser.fullscreen.autohide - Disable this.
** Joystick
*** Trying https://www.spinics.net/lists/usb/msg02644.html to see if the joystick doesn't freeze up during games.
*** TODO Read up
    https://ubuntuforums.org/archive/index.php/t-797789.html
** General
*** DNS
    - using systemd-resolved
    - Using nextdns. Get config text from next dns site
** Audio
https://shallowsky.com/linux/pulseaudio-command-line.html
*** When ps4 joystick pretends to sink sound.
pactl list short sources
pactl list
pactl info
pactl set-card-profile 10 off
pactl set-card-profile 1 output:analog-stereo
pactl set-card-profile 2 output:analog-stereo
pactl list short cards
** AUR/makepkg
Some issue with compiling GCC 10+ compiler. 
fix: Add '-fcommon' to CFLAGS in /etc/makepkg.conf
** nVidia Sheninigans
So one fine day, X stops loading complaining that nvidia module isn't loaded. 
Had to install nvidia-dkms package instead of nvidia for GPU drivers. The 'DKMS' bit recompiles the module to go into the kernel. With just the nvidia package, a new module wasn't being generated for 5.9.11 kernel.
pacman -Ql nvidia
modinfo nvidia
modprobe


* General notes
** Emacs
*** System Crafters videos
    Start emacs without any config. emacs -q
    Start emacs with specified config file: emacs -l some.el
*** This file will exist as part of my dotfiles repo.
** Mounting Disks
udiskie installed.
99-udisks2.rules added to /etc/udev/rules.d.
** Hibernation
/ is mounted on /dev/sda2. UUID: e5f5ad45-39e6-438d-9a6b-7f1efdc3667d ( blkid )
2893824 - File offset of /swapfile ( Found with filefrag or swap-offset )
Install https://wiki.archlinux.org/index.php/Uswsusp
- /etc/suspend.conf
Configure mkinitcpio.conf to include uresume and rebuild initramfs. (mkinitcpio -P )
** Browsing and transfering files from phone
- Make sure ADB mode is disabled on phone. (Or just use some adb commands. )
- Connect in MTP mode from phone.
- Use go-mtpfs-git AUR package
- `go-mtpfs mnt` - To mount it at /path/to/mnt.
** Media
*** mpv
Play videos in a smaller 'Picture in Picture' mode. (This is particularly useful when I'm working out while watching something. )
#+begin_src shell
mpv --ontop --no-border --autofit=384x216 --geometry=99%:2% [file]
mpv --ontop --no-border --on-all-workspaces --autofit=384x216 --geometry=99%:2% [file]
#+end_src
** Tailscale (VPN of sorts)
- This needs tunnel kernel module (modprobe tun). 
- Install networkmanager-vpnc to obtain it. On further analysis, not sure if this is needed.
- System needs a reboot after install all the packages.
- FOllow instructions in tailscale webpage. There's an AUR package. 
** Backups (Using borg)
s borg create --stats --one-file-system -C zstd,22 --progress --exclude-from /home/mkartic/dotfiles/borg_backup_root_ignore.txt root::Feb13_2021 /


